# Generated by Django 3.1.7 on 2021-05-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210530_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='transasaction_id',
            new_name='transaction_id',
        ),
    ]
